### ISSUE TITLE
Have builds for both PR's and FB's - but not both

### ISSUE THREAD

**Issue by mlennon-lumere** [ashwanthkumar/gocd-build-github-pull-requests#128]
We have users who want builds for both all of their Feature Branches and all of their Pull Requests (alongside the Github Pull Request Status Notifier plugin).

The trouble is, that for new commits to open PR's, each commit triggers two builds, one in our 'Feature Branch' pipeline and one in our 'Pull Request' pipeline.

Is there a way we can get things configured so that builds happen only once for commits to PR's?  Every PR comes from a Feature Branch.  Thanks!

**Comment by ashwanthkumar** [comment]
@mlennon-lumere One way I can think of is, you might want to consider the following

- Have a specific branch name convention for all PR branches
- Use that convention as a blacklist in the Git FB Plugin

Example, let's say you're working on a feature branch called `feature-a`. And assume you've a blacklist glob pattern in Git FB plugin as `pr-*`. 

Once the developer is done working on the feature branch and is ready to open a PR, they should create new branch with a convention like `pr-feature-a` and open a PR with that branch. 

You might choose to delete or discard the earlier `feature-a` branch. Going forward for any changes based on the PR comments, it can be done in the `pr-feature-a` branch. Since `pr-*` is a blacklist in FB plugin, it would never build that branch and only the PR based build pipeline would do so.

**Comment by mlennon-lumere** [comment]
Thank you for that suggestion - it is a good one!  Unfortunately it will need our users to take action and rename their FB to something like `pr-` before opening the PR, which is something that they probably will not like and not do.  They're used to how CircleCI works in this regard and we're moving to GoCD for other reasons but finding this a pain point.

Another way to attack it would be - do you know any way to configure the github PR notifier to work for feature branches that have PR's?

Otherwise we can 
- Only use FB plugin
- Hack together a script that pings the github API and if there is a PR for that FB, notify the PR of the status

Thanks again

**Comment by ashwanthkumar** [comment]
@mlennon-lumere I think you don't need to check if there's a PR open or not. If we've a Github Status Notifier that marks the commit as success or failure it would automatically reflect on the PR page.

**Comment by ashwanthkumar** [comment]
@mlennon-lumere I'm closing this issue since it's not directly related to this repo. Please feel free to re-open or comment if there's anything else I can help you with.
