### ISSUE TITLE
How is this supposed to work with gocd-yaml-config-plugin?

### ISSUE THREAD

**Issue by amilstead** [ashwanthkumar/gocd-build-github-pull-requests#160]
Specifically: https://github.com/tomzo/gocd-yaml-config-plugin

For example: What does a valid example configuration look like using the above plugin?

I have a problem: I expect changes to my `.gocd.yaml` file in a pull request to be reflected in the jobs executed by my GoCD server. Today, this does not happen.

Either I have configured something wrong, or this plugin simply does not support this behavior. I do not know the answer though, since I can't really find a reference point for how to use this plugin alongside gocd-yaml-config-plugin.

Is there a good reference point, or can you please provide one?

**Comment by ashwanthkumar** [comment]
May be [this comment](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/issues/117#issuecomment-646653062) should help. 

To your actual problem, the changes in the YAML will not be reflected in GoCD as part of the PR. Because the GoCD YAML Config Plugin doesn't know anything a Pull Request and this PR plugin doesn't know anything about YAML based configuration. YAML Plugin works directly with the GoCD Server's MCU (Material Check Update). So the configuration for a plugin is not changed unless the branch in the  config reference is changed.
